objects/Brand__c.object
<CustomObject>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product_Line__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Product Line</label>
        <referenceTo>Product_Line__c</referenceTo>
        <relationshipLabel>Brands</relationshipLabel>
        <relationshipName>Brands</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Brand</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Brand_Hierarchy__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Brand_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Brand Code</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipLabel>Brand Hierarchies</relationshipLabel>
        <relationshipName>Brand_Hierarchies</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Code__c</fullName>
        <description>it is only for Brand_Hierarchy_Outbound feed.</description>
        <formula>Brand_Code__r.Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Filter__c</fullName>
        <label>Filter</label>
        <picklist>
            <picklistValues>
                <fullName>2A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>500mA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>500mA - EU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>500mA - NZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>500mA - UK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Filtered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Filter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Flavormax</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GSAW-001</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LED Green</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LED Green - UK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LED Red</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LED Red - UK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Multifilter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N/A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Filtered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NULL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Plastic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unknown</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>US to EU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vapors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wood</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Flavor__c</fullName>
        <label>Flavor</label>
        <picklist>
            <picklistValues>
                <fullName>Absolute Tobacco</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amber</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Apple</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Berry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Black</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Blend No. 27</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Blue Mint</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bold Classic 4.5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bold Menthol 4.5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bold Original 4.5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bold Wintergreen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cherry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Citrus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Classic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Classic 2.4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Classic 2.5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cool Mint</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cool Mint Tobacco</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Crisp</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Crisp Blend</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Crisp Mint</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dark</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dark Blend</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fusion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fusion 2.5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Green Mint</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Harvest Blend</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Key</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Menthol</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Menthol 2.4</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Length__c</fullName>
        <label>Length</label>
        <picklist>
            <picklistValues>
                <fullName>100s</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>120s</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>72mm</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>83mm</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Black</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cube</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disposable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Flat Wire</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>King Size</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Long</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Long Size</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mini</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N/A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NULL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Size</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Plastic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Plug Adapter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Short</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Soft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stainless Steel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>STANDARD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TANK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unknown</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>White</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>XL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>XL LONG</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product_Line_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Line Code</label>
        <referenceTo>Product_Line__c</referenceTo>
        <relationshipLabel>Brand Hierarchies</relationshipLabel>
        <relationshipName>Brand_Hierarchies</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UPC__c</fullName>
        <label>UPC</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Brand Hierarchy</label>
    <nameField>
        <displayFormat>BH{0000}</displayFormat>
        <label>Brand Hierarchy Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brand Hierarchies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Product_Line__c.object
<CustomObject>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>isActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>isActive</label>
        <type>Checkbox</type>
    </fields>
    <label>Product Line</label>
    <nameField>
        <label>Product Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BrandHierarchyController.cls
/*
Functionality to select the Brand Hierarchy
06/30/2016 Infogain – Created.
*/

public with sharing class BrandHierarchyController {

    public String selectedProductLine {get; set;} /* String to hold Product Line */
    public List<SelectOption> productLineList {get; set;} /* List to hold Product Line data */
    public boolean showTable {get;set;} /* Flag to set if the brand hierarchy table should be visible or not. */
    public List<Brand_Hierarchy__c> brandHierarchyList{get; set;} /* List to hold Brand Hierarchy data */
    public List<SelectOption> brandList {get; set;} /* List to hold Brand data */    
    public String upcData {get;set;} /* String to hold UPC number */
    public String brandHierId {get;set;} /* String to hold Brand Hierarchy ID */
    public String brandData {get; set;} /* String to hold Brand data */
    private String productLine = apexpages.currentpage().getparameters().get('productlineName'); /* String to get Product Line Name */
    public String selectedUpc {get;set;} /* String to hold selected UPC Number */ 
     
    public BrandHierarchyController(ApexPages.StandardController controller){
        showTable = false;    
        brandHierarchyList = new List<Brand_Hierarchy__c>();
        brandList = new List<SelectOption>();
        brandHierId =  apexpages.currentpage().getparameters().get('brandHierId');
        
        productLineListData();
        brandListData();
    }
    
    /* Product line list */
    public void productLineListData(){
        
        productLineList = new List<SelectOption>(); 
         
        
        if(productLine != null && productLine != ''){        
        
            selectedProductLine = productLine;
            productLineList.add(new SelectOption(productLine, productLine));        
            
        }else{
            productLineList.add(new SelectOption('0', '--Select Product Line--',false)); 
            
            List<Product_Line__c> productLineObj = new List<Product_Line__c>([Select id, Name from Product_Line__c where isActive__c = true]);  
            
            for(Product_Line__c pl :productLineObj){
                productLineList.add(new SelectOption(pl.name, pl.name));
            }          
        }             
    }
    
     @RemoteAction
     public static List<String> productbrandList(String productLine, String UPC){
         List<String> brands = new List<String>();
         
         If(UPC != null && UPC != '' && UPC != '0'){
               AggregateResult[] groupedResults = [Select Count(id), Brand_code__r.Name, Brand_code__r.Code__c 
                                                    From Brand_Hierarchy__c 
                                                    Where Active__c = true and Product_Line_Code__r.Name =: productLine
                                                    and UPC__c = :UPC
                                                    Group by Brand_code__r.Name,Brand_code__r.Code__c];
        
                for (AggregateResult ar : groupedResults){
                    String brandName = String.ValueOf(ar.get('Name'));
                    brands.add(brandName);
                }
         }else{
             AggregateResult[] groupedResults = [Select Count(id), Brand_code__r.Name, Brand_code__r.Code__c 
                                                        From Brand_Hierarchy__c 
                                                        Where Active__c = true and Product_Line_Code__r.Name =: productLine
                                                        Group by Brand_code__r.Name,Brand_code__r.Code__c];
            
            for (AggregateResult ar : groupedResults){
                String brandName = String.ValueOf(ar.get('Name'));
                brands.add(brandName);
            }
        }
         
         return brands;
     }
    
    /* Create the Brand List from Brand Hierarchy data using aggregate method */
    public PageReference brandListData()
    { 
        if(selectedProductLine   != null && selectedProductLine  !=  '' && selectedProductLine != '0'){   
            brandList= new List<SelectOption>(); 
            brandList.add(new SelectOption('0', '--Select Brand--'));           
           
                AggregateResult[] groupedResults = [Select Count(id), Brand_code__r.Name, Brand_code__r.Code__c 
                                                    From Brand_Hierarchy__c 
                                                    Where Active__c = true and Product_Line_Code__r.Name =: selectedProductLine
                                                    Group by Brand_code__r.Name,Brand_code__r.Code__c];
        
                for (AggregateResult ar : groupedResults){
                    String brandName = String.ValueOf(ar.get('Name'));
                    brandList.add(new SelectOption(brandName, brandName));
                }
             
                if(brandHierId != null && brandHierId != '')
                    brandData = [Select Brand_code__r.Name From Brand_Hierarchy__c where Active__c = true and  id = :brandHierId ].Brand_code__r.Name;
                    
           brandHierData();
         }
         
         
         
         return null;                    
    }
    
    /* Initialize the Brand Hierarchy list */
    public void brandHierData(){
        brandHierarchyList=new List<Brand_Hierarchy__c> ();  
        upcData =  '';     
    }
    
    /* Fill the Brand Hierarchy data based on Product Line and UPC number */
    public Pagereference fillBrandHierarchy()
    {
        brandHierarchyList=new List<Brand_Hierarchy__c> ();
        brandHierarchyList = brandHierDataList('',productLine,'0','0','0','0','0','0','0',selectedUPC,'0');
        
        if(brandHierarchyList.size()<=1){
            showTable = false;    
        }else{
            showTable = true;    
        }
        if(brandHierarchyList.size()==0){
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error,'UPC Not Valid!!!'));
        }else if(brandHierarchyList.size()==1){
            ApexPages.getMessages().clear();
            brandData = brandHierarchyList[0].Brand_Code__r.Name;
        }
        return null;
    }
    
    /* Select the Brand Hierarchy data based on Filter */
    @RemoteAction
    public static List<Brand_Hierarchy__c> brandHierDataList(string brandHierId, string productLine, string brand, string filter, string taste, string length, string packaging, string flavor, string paperType, string upc, string cut){
        String query = 'Select Id, Brand_Code__c, Brand_Code__r.Name,Brand_Code__r.Description__c, Filter__c,Flavor__c, Length__c,Packaging__c,';
               query += ' Product_Line_Code__c,Product_Line_Code__r.Name, Cut__c, PaperType__c, Taste__c, UPC__c'; 
               query += ' From Brand_Hierarchy__c';

        if(brandHierId != null && brandHierId != '' && brandHierId!= '0'){
            query += ' where Active__c = true and id = \''+brandHierId +'\'';
        }else{
            query += ' where Active__c = true and Product_Line_Code__r.Name = \''+productline+'\'';
            
            if(brand != null && brand != '' && brand != '0'){
                query += ' and Brand_code__r.Name = \''+brand+'\'';
            }
            
            if(filter != null && filter != '' && filter != '0'){
                query += 'and Filter__c =\''+ filter +'\'';
            }
            
            if(taste != null && taste != '' && taste != '0'){
                query += 'and Taste__c =\''+ Taste +'\'';
            }
            
            if(upc  != null && upc  != '' && upc  != '0'){
                query += 'and UPC__c =\''+ upc +'\'';
            }
            
            if(length != null && length != '' && length != '0'){
                query += 'and Length__c =\''+ length  +'\'';
            }
            
            if(packaging != null && packaging != '' && packaging != '0'){
                query += 'and Packaging__c =\''+ packaging +'\'';
            }
            
            if(flavor != null && flavor != ''&& flavor != '0'){
                query += 'and Flavor__c =\''+ flavor+'\'';
            }
            
            if(paperType != null && paperType  != ''&& paperType != '0'){
                query += 'and PaperType__c =\''+ paperType+'\'';
            }
            
            if(cut != null && cut != ''&& cut != '0'){
                query += 'and Cut__c =\''+ cut+'\'';
            }           
            
        }
        System.debug('test '+query);
        List<sObject> sobjList = Database.query(query);                                                       
        List<Brand_Hierarchy__c> brandHierList = new List<Brand_Hierarchy__c>();
        brandHierList = (List<Brand_Hierarchy__c>)sobjList;
        System.debug('test brandHierList '+brandHierList);
        return brandHierList;
    }

    /* Reset Brand Hierarchy attributes */
    public PageReference reset() {
        showTable = false;    
        brandHierarchyList = new List<Brand_Hierarchy__c>();
        brandList = new List<SelectOption>();
        brandHierId =  '';
        
        productLineListData();
        brandListData();
        
        return null;
    }

}