objects/Case.object
<CustomObject>
    <fields>
        <fullName>Comment__c</fullName>
        <label>Comment</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Consumer_Age_Verified__c</fullName>
        <formula>Contact.AVF_GIID_Received__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Consumer Age Verified</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CustomerID__c</fullName>
        <description>Feed Outbound</description>
        <formula>Contact.CustomerID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Customer ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reimbursement_Count__c</fullName>
        <label>Reimbursement Count</label>
        <summaryForeignKey>Reimbursement__c.Issue__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <label>Survey</label>
        <picklist>
            <picklistValues>
                <fullName>Required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Applicable</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Incomplete</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Transaction__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Transaction</label>
        <referenceTo>Transaction_Management__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Update_Reason__c</fullName>
        <label>Update Reason</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>United States</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canada</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Afghanistan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Albania</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Algeria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Samoa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Andorra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Angola</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anguilla</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Antigua and Barbuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Argentina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Armenia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aruba</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Austria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Azerbaijan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahamas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahrain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bangladesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Barbados</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belarus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belgium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belize</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Benin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bermuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bhutan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bolivia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bonaire</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bosnia-Herzegovina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Botswana</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CustomerID__c</fullName>
        <displayFormat>{00000}</displayFormat>
        <label>Customer ID</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Customer_Type__c</fullName>
        <label>Customer Type</label>
        <picklist>
            <picklistValues>
                <fullName>PM EMPLOYEE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GOV AGENT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ATTORNEY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OTHER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ALTRIA EMPL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JMC EMPL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>USSTC EMPL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CONSUMER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wholesaler</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retailer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Field Sales Force</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <encrypted>true</encrypted>
        <label>State / Province</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <encrypted>true</encrypted>
        <label>Zip Code / Postal code</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Customer_Type__c.object
<CustomObject>
    <fields>
        <fullName>Customer_Type__c</fullName>
        <label>Customer Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <label>Customer Type</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Customer Type Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Type</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Survey__c.object
<CustomObject>
    <fields>
        <fullName>Survey_Name__c</fullName>
        <label>Survey Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Survey</label>
    <nameField>
        <displayFormat>{00}</displayFormat>
        <label>SurveyId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Survey_Issue__c.object
<CustomObject>
    <fields>
        <fullName>AnswerText__c</fullName>
        <description>It is only for Issue_Survey_Outbound feed.</description>
        <formula>Answer__r.Answer__c</formula>
        <label>AnswerText</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comment__c</fullName>
        <label>Comment</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Issue__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Issue</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Survey Issues</relationshipLabel>
        <relationshipName>Survey_Issues</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>QuestionText__c</fullName>
        <description>It is only for Issue_Survey_Outbound feed.</description>
        <formula>Question__r.Question__c</formula>
        <label>QuestionText</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Survey_Name__c</fullName>
        <description>It is only for Issue_Survey_Outbound feed.</description>
        <formula>Survey__r.Survey_Name__c</formula>
        <label>Survey Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipLabel>Survey Issues</relationshipLabel>
        <relationshipName>Survey_Issues</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Transaction__c</fullName>
        <label>Transaction Management</label>
        <referenceTo>Transaction_Management__c</referenceTo>
        <relationshipLabel>Survey Issues</relationshipLabel>
        <relationshipName>Survey_Issues</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>isActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>isActive</label>
        <type>Checkbox</type>
    </fields>
    <label>Survey Issue</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Survey Issue Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Issues</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Transaction_Management__c.object
<CustomObject>
    <label>Transaction Management</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Transaction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Managements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/IssueDetailController.cls
/*
Issue detail page controller class.
07/18/2016 Infogain – Created.
*/

   public class IssueDetailController {
    // Global declaration of variables
    private Id issueId;
    public Id tranId {get;set;}
    public Case caseObj {get;set;}
    public boolean isReimbursed{get;set;}
    private ApexPages.StandardController standardController;
    public boolean isUpdateReasonVisible{get;set;}
    public boolean isAgeVerified{get;set;}
    public string isSurveyApplicable {get;set;}
    id contactid;
    public String tranName {get;set;}
    public String custName {get;set;} 
    public string custId{get;set;}
    public string country{get;set;}
    public string customertype{get;set;}
    public string customerRecType{get;set;}
    public List<Attachment> attachList{get;set;} 
    public Integer PageSize  {get;set;}
    public id currentTran {get;set;}
    public List<Survey_Issue__c> IssueSurvyeList{get;set;} 
    public boolean isRepeatCom{get;set;}

    
   // Constructor
    public IssueDetailController(ApexPages.StandardController controller) {
           this.standardController = controller;
           this.caseObj = (Case)controller.getRecord();
           issueId =  this.caseObj.id;  
           IssueSurvyeList = new List<Survey_Issue__c>();
           custName  = '';
           custId = '';
           Case cValue = new Case();
           Cookie counter = ApexPages.currentPage().getCookies().get('tranid');
           if(counter != null) {
                currentTran = counter.getValue();
           }
           if(this.caseObj.id != null){
               cValue =  [Select id, Transaction__c, Survey__c, Transaction__r.Name,ContactId, Contact.Name,contact.Zip_Code__c,contact.State__c,contact.Country__c,
                               contact.Birthdate,Contact.CustomerID__c, Consumer_Age_Verified__c, Contact.Customer_Type__c  from Case where id =: caseObj.id];
               country=cValue.Contact.Country__c;
               customertype = cValue.Contact.Customer_Type__c;
               if(cValue.Transaction__c != null ){
                   tranId = cValue.Transaction__c;
                   tranName = cValue .Transaction__r.Name;  
               }
               
               if(cValue.ContactId != null){
                   custName = cValue.Contact.Name;
                   custId = cValue.Contact.CustomerID__c;
                   
               }
               isAgeVerified = cValue.Consumer_Age_Verified__c;
               
               if(cValue.Survey__c != null){
                   isSurveyApplicable = cValue.Survey__c;
               }

           }
           isReimbursed = checkMultipleReimbursements();
        
           
           if(caseObj.Update_Reason__c!=null && caseObj.Update_Reason__c!=''){
               isUpdateReasonVisible = true;
           }else{
               isUpdateReasonVisible =false;
           }
           
           counter = ApexPages.currentPage().getCookies().get('customerRecType');
           if(counter != null) {
                customerRecType = counter.getValue();
           }
        
        attachmentList();
        IssueSurveyData();
       }
    
    
    // Method for validation to avoid more than one reimbursement on same issue
    public boolean checkMultipleReimbursements(){
        Case currIssue = [Select Id, Reimbursement_Count__c From Case Where Id =: caseObj.id limit 1];

        if(currIssue != null && currIssue.Reimbursement_Count__c > 0)
        {
            return true;
        }  
        return false;
    }
    
    // Button event to create new store from current issue
    public PageReference store()
    {
        issueId = ApexPages.currentPage().getParameters().get('id');
        PageReference pg = new PageReference('/apex/StoreEditPage?IssueId='+ issueId);
        return pg;
    }

    // Button event to create new reimbursement from current issue    
    public Pagereference reimbursementNew()
    {
        issueId = ApexPages.currentPage().getParameters().get('id');
        PageReference pg = new PageReference('/apex/ReimbursementEdit?issueId='+ issueId);
        return pg;
    }
   
    // Button event to edit current issue
    public PageReference edit()
    {
       PageReference pg = new Pagereference('/apex/IssueEntryPage?id='+issueId);
       return pg;
    }
    
    // Button event to detail reimbursement of current issue
    /*public PageReference reimbursement(){
        Id id=ApexPages.currentPage().getParameters().get('id');
        PageReference reimbursement= new PageReference('/apex/reimbursement_IssueList');
        reimbursement.getParameters().put('Issid',ApexPages.currentPage().getParameters().get('id'));
        reimbursement.getParameters().put('tranId',ApexPages.currentPage().getParameters().get('tranId')); 
        reimbursement.setRedirect(true);
        return reimbursement;
    }*/
    
    //Method to get the creatable fields of a object and create a dynamic soql query.
    public static string getCreatableFieldsSOQL(String objectName, String whereClause){
        String selects = '';
        if (whereClause == null || whereClause == ''){ return null; }
        // Get a map of field name and field token
        Map<String, Schema.SObjectField> fMap = Schema.getGlobalDescribe().get(objectName.toLowerCase()).getDescribe().Fields.getMap();
        list<string> selectFields = new list<string>();
         if (fMap != null)
         {
            for (Schema.SObjectField ft : fMap.values())
            { 
            // loop through all field tokens (ft)
                Schema.DescribeFieldResult fd = ft.getDescribe(); // describe each field (fd)
                if (fd.isCreateable() && fd.getName() != 'Update_Reason__c')
                { // field is creatable
                   selectFields.add(fd.getName());
                }
            }
        }
         
        if (!selectFields.isEmpty())
        {
            for (string s:selectFields)
            {
                selects += s + ',';
            }
            if (selects.endsWith(','))
            {
            selects = selects.substring(0,selects.lastIndexOf(','));
            }
             
        }
        return 'SELECT ' + selects + ' FROM ' + objectName + ' WHERE ' + whereClause;
        }
  
    // Button event to create clone of current issue
    public PageReference customClone()
    {
        PageReference pgRef;
        Id cloneIssueId = ApexPages.currentPage().getParameters().get('id');
        String soql = getCreatableFieldsSOQL('case','id=: cloneIssueId');
        Case issueOld = (Case)Database.query(soql);
        Case issueNew = issueOld.clone(false, true);
        insert issueNew;
        if(contactid !=  null && contactid != ''){
            pgRef = new Pagereference('/apex/IssueEntryClone?id='+issueNew.id+'&parentIssue='+cloneIssueId+'&contid='+contactid );
        }else{
            pgRef = new Pagereference('/apex/IssueEntryClone?id='+issueNew.id+'&parentIssue='+cloneIssueId);
        }
        
        return pgRef;
    }
       
    public Pagereference attachmentList(){           
       
       attachList=[select id,name,CreatedDate,LastModifiedDate,description from Attachment where ParentId=:caseObj.id];
       
       return null;
    }
       
    public Pagereference  IssueSurveyData() {        
          
       IssueSurvyeList = new List<Survey_Issue__c>( [SELECT id, Comment__c, Survey_Name__c, QuestionText__c ,AnswerText__c 
                        FROM Survey_Issue__c 
                        Where isActive__c = true
                        and Issue__c =:caseObj.id 
                        order by createddate asc limit 5] );
        
        return null;
    } 
       
    
    
    public Pagereference ConsumerDetails(){
        Case cValue = new Case();
        if(caseObj.id != null){
           cValue =  [Select id, Transaction__c,Survey__c , Transaction__r.Name,Contact.Country__c,ContactId, Contact.Name,Contact.CustomerID__c,Consumer_Age_Verified__c, Contact.Customer_Type__c
                      From Case Where id =: caseObj.id];
           if(cValue.Transaction__c != null ){
               tranId = cValue.Transaction__c;
               tranName = cValue .Transaction__r.Name;  
           }
           System.debug('test cValue.Survey__c '+cValue.Survey__c);
           if(cValue.Survey__c != null){
               isSurveyApplicable = cValue.Survey__c;
           }
           
           if(cValue.ContactId != null){
               custName = cValue.Contact.Name;
               custId = cValue.Contact.CustomerID__c;
               country=cValue.Contact.Country__c;
               customertype =  cValue.Contact.Customer_Type__c;
           }
            
            isAgeVerified = cValue.Consumer_Age_Verified__c;
         }
       if(!isReimbursed)   
           isReimbursed = checkMultipleReimbursements();  
           
       attachmentList(); 
       IssueSurveyData();
       return null;
    }
}