objects/Case.object
<CustomObject>
    <fields>
        <fullName>Purchase_Price__c</fullName>
        <label>Purchase Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Taste__c</fullName>
        <label>Taste</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TenantId__c</fullName>
        <formula>&apos;ALORICAALTRIA&apos;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>TenantId</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Apt_Lot__c</fullName>
        <label>Apt / Lot</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <encrypted>true</encrypted>
        <label>City  / Locality</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <encrypted>true</encrypted>
        <label>State / Province</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_Address__c</fullName>
        <encrypted>true</encrypted>
        <label>Street Address / Address1</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TenantId__c</fullName>
        <formula>&apos;ALORICAALTRIA&apos;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>TenantId</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <encrypted>true</encrypted>
        <label>Zip Code / Postal code</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Correspondence__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Correspondences</relationshipLabel>
        <relationshipName>Correspondences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LetterDate__c</fullName>
        <description>Feed outbound- Correspondence</description>
        <label>Letter Date</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Received_Date__c</fullName>
        <description>Feed outbound- Correspondence</description>
        <label>Received Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TenantId__c</fullName>
        <description>Feed outbound- Correspondence</description>
        <formula>&apos;ALORICAALTRIA&apos;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>TenantId</label>
        <type>Text</type>
    </fields>
    <label>Correspondence</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Correspondence ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Correspondences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/DocumentType__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DocumentTypeCode__c</fullName>
        <label>DocumentTypeCode</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ReqFulfillment__c</fullName>
        <label>Requires Fulfillment</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TenantId__c</fullName>
        <formula>&apos;ALORICAALTRIA&apos;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>TenantId</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VendorCode__c</fullName>
        <label>Vendor Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>showMasterField__c</fullName>
        <defaultValue>false</defaultValue>
        <label>showMasterField</label>
        <type>Checkbox</type>
    </fields>
    <label>Document Type</label>
    <nameField>
        <displayFormat>DT-{0000000}</displayFormat>
        <label>Document Type Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Document Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CorrespondenceControllerTest.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
  Public class CorrespondenceControllerTest{
      static testmethod void CorrespondenceControllerTest1(){
      
      account acc=new account();
          acc.Name='priyanka';
          insert acc;
    
    contact con=new contact();
       con.FirstName='shweta';
       con.Salutation='ms';
       con.Accountid=acc.id;
       con.LastName='thakur';
       con.Apt_Lot__c='qwe';
       con.Street_Address__c='altria';
       con.City__c='meerut';    
       con.State__c='up';
       con.Zip_Code__c ='281004';             
       insert con;
       
   /*DocumentType__c dty=new DocumentType__c();
        dty.ReqFulfillment__c='Yes';
        dty.showMasterField__c=true;
        dty.Description__c='CRCNM05';
        dty.NAME='USSTC06- Call Me- Product Quality';
        dty.TenantId__c='AloricaAltria';
        dty.DocumentTypeCode__c='ALTRAMCRRCRRS';
        dty.VendorCode__c='PRC';
        dty.FLPPackage__c='Yes';
        dty.DocumentType__c='Outbound';
        insert dty;       */
    
   Correspondence__c crspdnc=new Correspondence__c();
      crspdnc.contact__c=con.id;
      crspdnc.Received_Date__c=system.today();
      crspdnc.LetterDate__c='system.today()';
      insert crspdnc;
            
           
    Case cs=new Case();
        cs.Taste__c='asd';
        cs.Purchase_Price__c=123;
        insert cs;       
          
  
     ApexPages.currentPage().getParameters().put('contid',con.id);
     ApexPages.StandardController std = new ApexPages.StandardController(crspdnc);    
     CorrespondenceController ac = new CorrespondenceController (std);     
      ac.conObj=con;
      ac.codObj=crspdnc;    
    //ac.codObj.Contact__c=con.id;
      ac.showMasterID=true;
      ac.selectedId='shweta'; 
      ac.Clear();
      //ac.getShowMasterField();        
      //ac.getRecord();      
      ac.SaveRecord();
      }
  }