objects/Case.object
<CustomObject>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Consumer Return Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Operating_Company__c</fullName>
        <formula>TEXT(Product_Line_Code__r.Operating_Company__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Operating Company</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <label>Survey</label>
        <picklist>
            <picklistValues>
                <fullName>Required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Applicable</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Incomplete</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Transaction__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Transaction</label>
        <referenceTo>Transaction_Management__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Operating_Company__c.object
<CustomObject>
    <fields>
        <fullName>Trade__c</fullName>
        <formula>ISPICKVAL(OperatingCompany__c, &apos;Trade&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Trade</label>
        <type>Checkbox</type>
    </fields>
    <label>Operating Company</label>
    <nameField>
        <displayFormat>OpCo - {00000}</displayFormat>
        <label>OperatingCompany</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Operating Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Survey__c.object
<CustomObject>
    <label>Survey</label>
    <nameField>
        <displayFormat>{00}</displayFormat>
        <label>SurveyId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Transaction_Management__c.object
<CustomObject>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Transaction Managements</relationshipLabel>
        <relationshipName>Transaction_Managements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Disposition__c</fullName>
        <label>Disposition</label>
        <picklist>
            <picklistValues>
                <fullName>Chat Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Do Not Call(Add Details To CCC/Agent Notes)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Escalation Research</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hang Up/ Dead Air Disconnect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Language Barrier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prank Caller</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prank Caller/ Wrong Number</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Schedule Callback</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Test Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transferred Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wrong Number</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>End_Date_Time__c</fullName>
        <label>End Date Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Operating_Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Operating Company</label>
        <referenceTo>Operating_Company__c</referenceTo>
        <relationshipLabel>Transaction Managements</relationshipLabel>
        <relationshipName>Transaction_Managements</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Transaction Management</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Transaction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Managements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/EndCallController.cls
/* End Call edit Page Controller
   08/22/2016 - Infogain---Created
*/

 public class EndCallController {
 
    public Transaction_Management__c tranObj{get;set;}
    private String tranId{get;set;}
    public boolean isError {get;set;}
     
    
    
    public EndCallController(ApexPages.StandardController stdController) {
        Cookie counter = ApexPages.currentPage().getCookies().get('tranid');
        tranObj=new Transaction_Management__c();
        isError = false;
        if(counter != null) {
            tranId = counter.getValue();
            EndCallValidationMessage(tranId); 
            
        }
    }
    
    public void EndCallValidationMessage(String tranId){
        
       List<Transaction_Management__c> TmObj = new List<Transaction_Management__c>([select id,Disposition__c, Comments__c, Contact__c,End_Date_Time__c,Operating_Company__c, Operating_Company__r.Trade__c  
                                                                                    from Transaction_Management__c 
                                                                                    where id =: TranId]);
                                                                                    
         if(!TmObj.isEmpty() &&  TmObj[0].Operating_Company__c != null){
         
            tranObj = TmObj[0];
              
             List<Case> issueList = new List<Case>([Select Id,Survey__c from Case where Transaction__c =: TmObj[0].id and Survey__c =: 'Required']);
             
             if(TmObj[0].Contact__c == null){
                 isError = true;
                  if(TmObj[0].Operating_Company__r.Trade__c){
                      ApexPages.addMessage(new ApexPages.Message(apexpages.severity.Error,'Please select the trade customer for which the issue is created'));
                  }else{
                      ApexPages.addMessage(new ApexPages.Message(apexpages.severity.Error,'Please select the consumer for which the issue is created'));
                  }
             }
             
             if(!issueList.isEmpty()){
                  ApexPages.addMessage(new ApexPages.Message(apexpages.severity.Error,'Please present the survey or select a Cancel Reason')); 
                  isError =  true;                  
             }         
         }  
    }
    public void customSave(){
        try{
            tranObj.End_Date_Time__c = system.now();
            Database.SaveResult saverst = Database.update(tranObj);
            if(tranObj != null){
                 system.debug('=======tranObj======'+tranObj);
                 TransactionMgmtHelper mgmtHelper = new TransactionMgmtHelper();
                 mgmtHelper.createTransactionMgmtHistoryRecord('ENDCALL',saverst.getId());
             }
             Cookie counter = new Cookie('tranid', null,null,0,true);
             tranId = null;
         }catch(DMLException e){ 
            ApexPages.addMessages(e);
        }
    }     
 }