objects/Case.object
<CustomObject>
    <fields>
        <fullName>Brandcode__c</fullName>
        <label>Brand Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Causetxt__c</fullName>
        <label>Cause</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Classificationtxt__c</fullName>
        <label>Classification</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comment__c</fullName>
        <label>Comment</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>IsReviewed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsReviewed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Issue_Type__c</fullName>
        <label>Issue Type</label>
        <length>225</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Line__c</fullName>
        <label>Product Line</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reasontxt__c</fullName>
        <label>Reason</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Issue_Type__c.object
<CustomObject>
    <label>Issue Type</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Issue Type ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IssueTypes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Product_Line__c.object
<CustomObject>
    <label>Product Line</label>
    <nameField>
        <label>Product Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/IssueReviewController.cls
public class IssueReviewController{
    
    public Case issueObj {get; set;}
    public Integer PageSize{get;set;}
    
    public IssueReviewController(ApexPages.StandardController controller) {
        pageInit();
    }
    
    private void pageInit(){
                
        //issueObj = [select id,caseNumber from case where id=:ApexPages.currentPage().getParameters().get('Id')];
        if(ApexPages.currentPage().getParameters().get('pageSize') != null){
            PageSize = Integer.valueOf(ApexPages.currentPage().getParameters().get('pageSize'));
        }else{
            PageSize = 25;
        }
    }
    
     public ApexPages.StandardSetController setQun {
         
        get {
            if(setQun == null) {
                setQun = new ApexPages.StandardSetController(Database.getQueryLocator(
                    [SELECT id, CaseNumber, Issue_Type__c, Comment__c, ContactId, Brandcode__c, Product_Line__c, 
                     Classificationtxt__c, Reasontxt__c, Causetxt__c, Contact.Name 
                        FROM Case 
                        Where IsReviewed__c = false 
                        order by createddate asc] ));
                
                setQun.setPageSize(PageSize);
 
            }
            return setQun;
        }
        set;
    }
        
    public Boolean hasNext {
        get {
            return setQun.getHasNext();
        }
        set;
    }
    public Boolean hasPrevious {
        get {
            return setQun.getHasPrevious();
        }
        set;
    }
    
    public void previous() {
         setQun.previous();
     }
    
    public void next() {
         setQun.next();
     }
    
    
    // Wrapper list  
    public List<Case> getIssueReviewList() {        
          
        List<Case> issueList = new List<Case>();
        issueList =setQun.getRecords();
        
        return issueList ;
    } 
       
     public pagereference cancel(){
          return new PageReference('/'+issueObj.id);
     }
    
}