objects/Case.object
<CustomObject>
    <fields>
        <fullName>Operating_Company__c</fullName>
        <formula>TEXT(Product_Line_Code__r.Operating_Company__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Operating Company</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transaction__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Transaction</label>
        <referenceTo>Transaction_Management__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>AV_Code__c</fullName>
        <label>AV Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Apt_Lot__c</fullName>
        <label>Apt / Lot</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Birthdate__c</fullName>
        <encrypted>true</encrypted>
        <label>DOB</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCN__c</fullName>
        <encrypted>true</encrypted>
        <label>CCN</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <encrypted>true</encrypted>
        <label>City  / Locality</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>United States</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canada</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Afghanistan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Albania</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Algeria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Samoa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Andorra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Angola</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anguilla</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Antigua and Barbuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Argentina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Armenia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aruba</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Austria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Azerbaijan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahamas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahrain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bangladesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Barbados</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belarus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belgium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belize</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Benin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bermuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bhutan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bolivia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bonaire</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bosnia-Herzegovina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Botswana</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Email_Address__c</fullName>
        <encrypted>true</encrypted>
        <label>Email Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Operating_Company__c</fullName>
        <label>Operating Company</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <encrypted>true</encrypted>
        <label>State / Province</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_Address__c</fullName>
        <encrypted>true</encrypted>
        <label>Street Address / Address1</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <encrypted>true</encrypted>
        <label>Zip Code / Postal code</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Consumer</fullName>
        <active>true</active>
        <label>Consumer</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Operating_Company__c.object
<CustomObject>
    <fields>
        <fullName>OperatingCompany__c</fullName>
        <label>Operating Company</label>
        <picklist>
            <picklistValues>
                <fullName>PMUSA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JMC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NUMRK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>USST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CRC Direct</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trade</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Operating Company</label>
    <nameField>
        <displayFormat>OpCo - {00000}</displayFormat>
        <label>OperatingCompany</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Operating Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TFN__c.object
<CustomObject>
    <fields>
        <fullName>Operating_Company__c</fullName>
        <label>Operating Company</label>
        <referenceTo>Operating_Company__c</referenceTo>
        <relationshipLabel>Toll Free Number</relationshipLabel>
        <relationshipName>Toll_Free_Number</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>TFN</label>
    <nameField>
        <displayFormat>TFN-{0000}</displayFormat>
        <label>TFN Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Toll Free Number</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Transaction_Management__c.object
<CustomObject>
    <fields>
        <fullName>Operating_Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Operating Company</label>
        <referenceTo>Operating_Company__c</referenceTo>
        <relationshipLabel>Transaction Managements</relationshipLabel>
        <relationshipName>Transaction_Managements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TFN__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>DNIS</label>
        <referenceTo>TFN__c</referenceTo>
        <relationshipLabel>Transaction Managements</relationshipLabel>
        <relationshipName>Transaction_Managements</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Transaction Management</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Transaction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Managements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ConsumerEntryControllerTest.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
/*
test class of Consumer Entry
08/03/2016 Infogain – Created.
*/


  @isTest()
  private class ConsumerEntryControllerTest{
  //  Validate Constructor
   static testMethod void validateConsumerEntryController()
    {
        Account testAcc = TestDataSetup.createAccount('Test Account');
        insert testAcc ;
        Date bdate = Date.newInstance(1989, 06, 14);
        Contact testCont = TestDataSetup.createContact('Test Fname','Test Lname',testAcc.Id,true,'20001',bdate,'Test Street', true, true);
        testCont.Email = 'test123@test.com';
        insert testCont;
        Operating_Company__c testOpCo= TestDataSetup.createOpCo('Telephone', 'Phone USST','Inbound','  PMUSA',true);
        insert testOpCo;
        TFN__c testTFN = TestDataSetup.createTFN(true, '1800', 45, testOpCo);
        insert testTFN;
        Transaction_Management__c testTM= TestDataSetup.createTM(testOpCo, testTFN);
        insert testTM;
        Cookie tranId = ApexPages.currentPage().getCookies().get('tranId');
    
        // If this is the first time the user is accessing the page, 
        // create a new cookie with name 'counter', an initial value of '1', 
        // path 'null', maxAge '-1', and isSecure 'false'. 
        
         tranId = new Cookie('tranId',testTM.id,null,-1,false);
        
        // If this isn't the first time the user is accessing the page
        // create a new cookie, incrementing the value of the original count by 1
        // Set the new cookie for the page
         ApexPages.currentPage().setCookies(new Cookie[]{tranId});
         ApexPages.currentPage().getParameters().put('tranid', testTM.Id);
         ApexPages.currentPage().getParameters().put('Fname',testCont.Id);
         ApexPages.currentPage().getParameters().put('email',testCont.Email);
         Test.startTest();
         ConsumerEntryController controller = new ConsumerEntryController(new ApexPages.StandardController(testCont));
         controller.init();
         Test.stopTest();
         System.assertEquals('Fname', controller.conObj.FirstName );
     }
     // validate Getcitystate method
     static testMethod void validateGetcitystate() 
     {
        Account testAcc = TestDataSetup.createAccount('Test Account');
        insert testAcc ;
        Date bdate = Date.newInstance(1989, 06, 14);
        Contact testCont = TestDataSetup.createContact('Test Fname','Test Lname',testAcc.Id,true,'35801',bdate,'Test Street', true, true);
        testCont.Country__c = 'United States';
        testCont.City__c = 'Huntsville';
        insert testCont;
        Operating_Company__c testOpCo= TestDataSetup.createOpCo('Telephone', 'Phone USST','Inbound','  PMUSA',true);
        insert testOpCo;
        TFN__c testTFN = TestDataSetup.createTFN(true, '1800', 45, testOpCo);
        insert testTFN;
        Transaction_Management__c testTM= TestDataSetup.createTM(testOpCo, testTFN);
        insert testTM;
        ApexPages.currentPage().getParameters().put('tranid', testTM.Id);
        Test.startTest();
        ConsumerEntryController controller = new ConsumerEntryController(new ApexPages.StandardController(testCont));
        controller.getcitystate();
        Test.stopTest();
        //System.assertEquals(testTM.Id, controller.testTM.id );
      }
       // validate Getcitystate method
      static testMethod void validateGetcitystate1()
       {
         Account testAcc = TestDataSetup.createAccount('Test Account');
         insert testAcc ;
         Date bdate = Date.newInstance(1989, 06, 14);
         Contact testCont = TestDataSetup.createContact('Test Fname','Test Lname',testAcc.Id,true,'20001',bdate,'Test Street', true, true);
         insert testCont;
         Operating_Company__c testOpCo= TestDataSetup.createOpCo('Telephone', 'Phone USST','Inbound','  PMUSA',true);
         insert testOpCo;
         ApexPages.currentPage().getParameters().put('Fname',testCont.Id);
         Test.startTest();
         ConsumerEntryController controller = new ConsumerEntryController(new ApexPages.StandardController(testCont));
         controller.getcitystate();
         Test.stopTest();
          System.assertEquals('Fname', controller.conObj.FirstName );
         
       }
        // validate Getcitystate method
     static testMethod void validateGetcitystate2() 
      {
        Account testAcc = TestDataSetup.createAccount('Test Account');
        insert testAcc ;
        Date bdate = Date.newInstance(1989, 06, 14);
        Contact testCont = TestDataSetup.createContact('Test Fname','Test Lname',testAcc.Id,true,'20001',bdate,'Test Street', true, true);
        insert testCont;
         Operating_Company__c testOpCo= TestDataSetup.createOpCo('Telephone', 'Phone USST','Inbound','  PMUSA',true);
        insert testOpCo;
        ApexPages.currentPage().getParameters().put('Lname',testCont.Id);
        Test.startTest();
            ConsumerEntryController controller = new ConsumerEntryController(new ApexPages.StandardController(testCont));
            controller.getcitystate();
        Test.stopTest();
         System.assertEquals('Lname', controller.conObj.LastName );
     }
      // validate Getcitystate method
      static testMethod void validateGetcitystate3() 
      {
        Account testAcc = TestDataSetup.createAccount('Test Account');
        insert testAcc ;
        Date bdate = Date.newInstance(1989, 06, 14);
        Contact testCont = TestDataSetup.createContact('Test Fname','Test Lname',testAcc.Id,true,'20001',bdate,'Test Street', true, true);
        insert testCont;
        Operating_Company__c testOpCo= TestDataSetup.createOpCo('Telephone', 'Phone USST','Inbound','  PMUSA',true);
        insert testOpCo;
        ApexPages.currentPage().getParameters().put('Title',testCont.Id);
        Test.startTest();
        ConsumerEntryController controller = new ConsumerEntryController(new ApexPages.StandardController(testCont));
        controller.getcitystate();
        Test.stopTest();
        System.assertEquals('Title', controller.conObj.Title );
        
      }
       // validate Getcitystate method
       static testMethod void validateGetcitystate4() 
       {
         Account testAcc = TestDataSetup.createAccount('Test Account');
         insert testAcc ;
         Date bdate = Date.newInstance(1989, 06, 14);
         Contact testCont = TestDataSetup.createContact('Test Fname','Test Lname',testAcc.Id,true,'20001',bdate,'Test Street', true, true);
         insert testCont;
         Operating_Company__c testOpCo= TestDataSetup.createOpCo('Telephone', 'Phone USST','Inbound','  PMUSA',true);
         insert testOpCo;
         ApexPages.currentPage().getParameters().put('Addr1',testCont.Id);
         Test.startTest();
         ConsumerEntryController controller = new ConsumerEntryController(new ApexPages.StandardController(testCont));
         controller.getcitystate();
         Test.stopTest();
          //System.assertEquals('Addr1', controller.conObj.OtherAddress);
        
         
        }
         // validate Getcitystate method
        static testMethod void validateGetcitystate5() 
        {
         Account testAcc = TestDataSetup.createAccount('Test Account');
         insert testAcc ;
         Date bdate = Date.newInstance(1989, 06, 14);
         Contact testCont = TestDataSetup.createContact('Test Fname','Test Lname',testAcc.Id,true,'20001',bdate,'Test Street', true, true);
         insert testCont;
         Operating_Company__c testOpCo= TestDataSetup.createOpCo('Telephone', 'Phone USST','Inbound','  PMUSA',true);
         insert testOpCo;
         ApexPages.currentPage().getParameters().put('add',testCont.Id);
         Test.startTest();
         ConsumerEntryController controller = new ConsumerEntryController(new ApexPages.StandardController(testCont));
         controller.getcitystate();
         Test.stopTest();
         //System.assertEquals('add', controller.conObj.Address );
        }
         // validate Getcitystate method
        static testMethod void validateGetcitystate6() 
        {
         Account testAcc = TestDataSetup.createAccount('Test Account');
         insert testAcc ;
         Date bdate = Date.newInstance(1989, 06, 14);
         Contact testCont = TestDataSetup.createContact('Test Fname','Test Lname',testAcc.Id,true,'20001',bdate,'Test Street', true, true);
         insert testCont;
         Operating_Company__c testOpCo= TestDataSetup.createOpCo('Telephone', 'Phone USST','Inbound','  PMUSA',true);
         insert testOpCo;
         ApexPages.currentPage().getParameters().put('City',testCont.Id);
         Test.startTest();
         ConsumerEntryController controller = new ConsumerEntryController(new ApexPages.StandardController(testCont));
         controller.getcitystate();
         Test.stopTest();
         System.assertEquals('City', controller.conObj.City__c );

        }
         // validate Getcitystate method
        static testMethod void validateGetcitystate7()
         {
         Account testAcc = TestDataSetup.createAccount('Test Account');
         insert testAcc ;
         Date bdate = Date.newInstance(1989, 06, 14);
         Contact testCont = TestDataSetup.createContact('Test Fname','Test Lname',testAcc.Id,true,'20001',bdate,'Test Street', true, true);
         insert testCont;
         Operating_Company__c testOpCo= TestDataSetup.createOpCo('Telephone', 'Phone USST','Inbound','  PMUSA',true);
         insert testOpCo;
         ApexPages.currentPage().getParameters().put('State',testCont.Id);
         Test.startTest();
         ConsumerEntryController controller = new ConsumerEntryController(new ApexPages.StandardController(testCont));
         controller.getcitystate();
         Test.stopTest();
         System.assertEquals('State', controller.conObj.State__c );

         }
          // validate Getcitystate method
        static testMethod void validateGetcitystate8() 
        {
         Account testAcc = TestDataSetup.createAccount('Test Account');
         insert testAcc ;
         Date bdate = Date.newInstance(1989, 06, 14);
         Contact testCont = TestDataSetup.createContact('Test Fname','Test Lname',testAcc.Id,true,'20001',bdate,'Test Street', true, true);
         insert testCont;
         Operating_Company__c testOpCo= TestDataSetup.createOpCo('Telephone', 'Phone USST','Inbound','  PMUSA',true);
         insert testOpCo;
         ApexPages.currentPage().getParameters().put('dob',testCont.Birthdate__c);
         Test.startTest();
         ConsumerEntryController controller = new ConsumerEntryController(new ApexPages.StandardController(testCont));
         controller.getcitystate();
         Test.stopTest();
          System.assertEquals('dob', controller.conObj.Birthdate__c );
         }
          // validate Getcitystate method
        static testMethod void validateGetcitystate9() 
        {
          Account testAcc = TestDataSetup.createAccount('Test Account');
          insert testAcc ;
          Date bdate = Date.newInstance(1989, 06, 14);
          Contact testCont = TestDataSetup.createContact('Test Fname','Test Lname',testAcc.Id,true,'20001',bdate,'Test Street', true, true);
          insert testCont;
          Operating_Company__c testOpCo= TestDataSetup.createOpCo('Telephone', 'Phone USST','Inbound','  PMUSA',true);
         insert testOpCo;
         ApexPages.currentPage().getParameters().put('phone',testCont.Id);
         Test.startTest();
         ConsumerEntryController controller = new ConsumerEntryController(new ApexPages.StandardController(testCont));
         controller.getcitystate();
        Test.stopTest();
         System.assertEquals('phone', controller.conObj.Phone );
         }
          // validate Getcitystate method
        static testMethod void validateGetcitystate10() 
        {
         Account testAcc = TestDataSetup.createAccount('Test Account');
         insert testAcc ;
         Date bdate = Date.newInstance(1989, 06, 14);
         Contact testCont = TestDataSetup.createContact('Test Fname','Test Lname',testAcc.Id,true,'20001',bdate,'Test Street', true, true);
         insert testCont;
         Operating_Company__c testOpCo= TestDataSetup.createOpCo('Telephone', 'Phone USST','Inbound','  PMUSA',true);
         insert testOpCo;
         ApexPages.currentPage().getParameters().put('CCN',testCont.Id);
         Test.startTest();
         ConsumerEntryController controller = new ConsumerEntryController(new ApexPages.StandardController(testCont));
         controller.getcitystate();
         Test.stopTest();
          System.assertEquals('CCN', controller.conObj.CCN__c);
         }
          // validate Getcitystate method
        static testMethod void validateGetcitystate11()
         {
         Account testAcc = TestDataSetup.createAccount('Test Account');
         insert testAcc ;
         Date bdate = Date.newInstance(1989, 06, 14);
         Contact testCont = TestDataSetup.createContact('Test Fname','Test Lname',testAcc.Id,true,'20001',bdate,'Test Street', true, true);
         insert testCont;
         Operating_Company__c testOpCo= TestDataSetup.createOpCo('Telephone', 'Phone USST','Inbound','  PMUSA',true);
         insert testOpCo;
         ApexPages.currentPage().getParameters().put('strAVCode',testCont.Id);
         Test.startTest();
         ConsumerEntryController controller = new ConsumerEntryController(new ApexPages.StandardController(testCont));
         controller.getcitystate();
         Test.stopTest();
         System.assertEquals('strAVCode', controller.conObj.AV_Code__c);
         }
          // validate Getcitystate method
       static testMethod void validateGetcitystate12()
        {
         Account testAcc = TestDataSetup.createAccount('Test Account');
         insert testAcc ;
         Date bdate = Date.newInstance(1989, 06, 14);
         Contact testCont = TestDataSetup.createContact('Test Fname','Test Lname',testAcc.Id,true,'20001',bdate,'Test Street', true, true);
         insert testCont;
         Operating_Company__c testOpCo= TestDataSetup.createOpCo('Telephone', 'Phone USST','Inbound','  PMUSA',true);
         insert testOpCo;
         ApexPages.currentPage().getParameters().put('email',testCont.Id);
         Test.startTest();
         ConsumerEntryController controller = new ConsumerEntryController(new ApexPages.StandardController(testCont));
         controller.getcitystate();
         Test.stopTest();
          System.assertEquals('email', controller.conObj.Email);
        }
         // validate Getcitystate method
       static testMethod void validateGetcitystate13() 
       {
        Account testAcc = TestDataSetup.createAccount('Test Account');
        insert testAcc ;
        Date bdate = Date.newInstance(1989, 06, 14);
        Contact testCont = TestDataSetup.createContact('Test Fname','Test Lname',testAcc.Id,true,'20001',bdate,'Test Street', true, true);
        insert testCont;
        Operating_Company__c testOpCo= TestDataSetup.createOpCo('Telephone', 'Phone USST','Inbound','  PMUSA',true);
        insert testOpCo;
        ApexPages.currentPage().getParameters().put('country',testCont.Id);
        Test.startTest();
        ConsumerEntryController controller = new ConsumerEntryController(new ApexPages.StandardController(testCont));
        controller.getcitystate();
        Test.stopTest();
        System.assertEquals('country', controller.conObj.Country__c);
        }
         // validate Getcitystate method
      static testMethod void validateGetcitystate14()
       {
        Account testAcc = TestDataSetup.createAccount('Test Account');
        insert testAcc ;
        Date bdate = Date.newInstance(1989, 06, 14);
        Contact testCont = TestDataSetup.createContact('Test Fname','Test Lname',testAcc.Id,true,'20001',bdate,'Test Street', true, true);
        insert testCont;
        Operating_Company__c testOpCo= TestDataSetup.createOpCo('Telephone', 'Phone USST','Inbound','  PMUSA',true);
        insert testOpCo;
        ApexPages.currentPage().getParameters().put('Zip',testCont.Id);
        Test.startTest();
        ConsumerEntryController controller = new ConsumerEntryController(new ApexPages.StandardController(testCont));
        controller.getcitystate();
        Test.stopTest();
        System.assertEquals('Zip', controller.conObj.Zip_Code__c);
        }
       // validate GetaddressverifiedUS method
       static testMethod void validateGetaddressverifiedUS()
        {
        Account testAcc = TestDataSetup.createAccount('Test Account');
        insert testAcc ;
        Date bdate = Date.newInstance(1989, 06, 14);
        Contact testCont = TestDataSetup.createContact('Test Fname','Test Lname',testAcc.Id,true,'20001',bdate,'Test Street', true, true);
        testCont.Country__c = 'United States';
        testCont.City__c = 'Grand Rapids';
        testCont.State__c = 'Michigan';
        insert testCont;
        Operating_Company__c testOpCo= TestDataSetup.createOpCo('Telephone', 'Phone USST','Inbound','PMUSA',true);
        insert testOpCo;
        Test.startTest();
        ConsumerEntryController controller = new ConsumerEntryController(new ApexPages.StandardController(testCont));
        controller.getaddressverified();
        Test.stopTest();
        //System.assertEquals('PMUSA', controller.testOpCo.OperatingCompany__c);
        }
       // validate Getaddressverified method 
       static testMethod void validateGetaddressverified() 
        {
         Account testAcc = TestDataSetup.createAccount('Test Account');
         insert testAcc ;
         Date bdate = Date.newInstance(1989, 06, 14);
         Contact testCont = TestDataSetup.createContact('Test Fname','Test Lname',testAcc.Id,true,'20001',bdate,'Test Street', true, true);
         insert testCont;
         Operating_Company__c testOpCo= TestDataSetup.createOpCo('Telephone', 'Phone USST','Inbound','  PMUSA',true);
         insert testOpCo;
         Test.startTest();
         ConsumerEntryController controller = new ConsumerEntryController(new ApexPages.StandardController(testCont));
         controller.getaddressverified();
         Test.stopTest();
          //System.assertEquals('PMUSA', controller.testOpCo.OperatingCompany__c);
        }
        // validate Getglobaladdverify method
       static testMethod void validateGetglobaladdverify() 
       {
        Account testAcc = TestDataSetup.createAccount('Test Account');
        insert testAcc ;
        Date bdate = Date.newInstance(1989, 06, 14);
        Contact testCont = TestDataSetup.createContact('Test Fname','Test Lname',testAcc.Id,true,'20001',bdate,'Test Street', true, true);
        insert testCont;
        Operating_Company__c testOpCo= TestDataSetup.createOpCo('Telephone', 'Phone USST','Inbound','  PMUSA',true);
        insert testOpCo;
        Test.startTest();
        ConsumerEntryController controller = new ConsumerEntryController(new ApexPages.StandardController(testCont));
        //controller.getglobaladdverify();
        Test.stopTest();
        }
        // validate SaveNoContact method
       static testMethod void validateSaveNoContact() 
        {
         Account testAcc = TestDataSetup.createAccount('Test Account');
         insert testAcc ;
         Date bdate = Date.newInstance(1989, 06, 14);
         Contact testCont = TestDataSetup.createContact('Test Fname','Test Lname',testAcc.Id,true,'20001',bdate,'Test Street', true, true);
         //insert testCont;
         Operating_Company__c testOpCo= TestDataSetup.createOpCo('Telephone', 'Phone USST','Inbound','  PMUSA',true);
         insert testOpCo;
         TFN__c testTFN = TestDataSetup.createTFN(true, '1800', 45, testOpCo);
         insert testTFN;
         Transaction_Management__c testTM= TestDataSetup.createTM(testOpCo, testTFN);
         insert testTM;
         Case testCase = TestDataSetup.createTestCase(testAcc, 1200, testCont.Id);
         testCase.Transaction__c = testTM.Id;
         insert testCase;
         ApexPages.currentPage().getParameters().put('from','Search');
        /*ApexPages.currentPage().getParameters().put('Fname',testCont.FirstName);
        ApexPages.currentPage().getParameters().put('Lname',testCont.LastName);
        ApexPages.currentPage().getParameters().put('Title',testCont.Title);
        ApexPages.currentPage().getParameters().put('Addr1',testCont.Apt_Lot__c);
        ApexPages.currentPage().getParameters().put('add',testCont.Street_Address__c);
        ApexPages.currentPage().getParameters().put('City',testCont.City__c);
        ApexPages.currentPage().getParameters().put('State',testCont.State__c);
        ApexPages.currentPage().getParameters().put('dob',testCont.Birthdate__c);
        ApexPages.currentPage().getParameters().put('zip',testCont.Zip_Code__c);
        ApexPages.currentPage().getParameters().put('CCN',testCont.CCN__c);
        ApexPages.currentPage().getParameters().put('strAVCode',testCont.AV_Code__c);
        ApexPages.currentPage().getParameters().put('email',testCont.Email_Address__c);
        ApexPages.currentPage().getParameters().put('country',testCont.Country__c);
        ApexPages.currentPage().getParameters().put('phone',testCont.Phone);*/
        ApexPages.currentPage().getParameters().put('tranid',testTM.Id);
        Test.startTest();
        ConsumerEntryController controller = new ConsumerEntryController(new ApexPages.StandardController(testCont));
        controller.save();
        Test.stopTest();
       }
      // validate Save method
      static testMethod void validateSave()
       {
        Account testAcc = TestDataSetup.createAccount('Test Account');
        insert testAcc ;
        Date bdate = Date.newInstance(1989, 06, 14);
        Contact testCont = TestDataSetup.createContact('Test Fname','Test Lname',testAcc.Id,true,'20011',bdate,'Test Street', true, true);
        insert testCont;
        Operating_Company__c testOpCo= TestDataSetup.createOpCo('Telephone', 'Phone USST','Inbound','  PMUSA',true);
        insert testOpCo;
        TFN__c testTFN = TestDataSetup.createTFN(true, '1800', 45, testOpCo);
        insert testTFN;
        Transaction_Management__c testTM= TestDataSetup.createTM(testOpCo, testTFN);
        insert testTM;
        Case testCase = TestDataSetup.createTestCase(testAcc, 1200, testCont.Id);
        testCase.Transaction__c = testTM.Id;
        insert testCase;
        ApexPages.currentPage().getParameters().put('from','Search');
        /*ApexPages.currentPage().getParameters().put('Fname',testCont.FirstName);
        ApexPages.currentPage().getParameters().put('Lname',testCont.LastName);
        ApexPages.currentPage().getParameters().put('Title',testCont.Title);
        ApexPages.currentPage().getParameters().put('Addr1',testCont.Apt_Lot__c);
        ApexPages.currentPage().getParameters().put('add',testCont.Street_Address__c);
        ApexPages.currentPage().getParameters().put('City',testCont.City__c);
        ApexPages.currentPage().getParameters().put('State',testCont.State__c);
        ApexPages.currentPage().getParameters().put('dob',testCont.Birthdate__c);
        ApexPages.currentPage().getParameters().put('zip',testCont.Zip_Code__c);
        ApexPages.currentPage().getParameters().put('CCN',testCont.CCN__c);
        ApexPages.currentPage().getParameters().put('strAVCode',testCont.AV_Code__c);
        ApexPages.currentPage().getParameters().put('email',testCont.Email_Address__c);
        ApexPages.currentPage().getParameters().put('country',testCont.Country__c);
        ApexPages.currentPage().getParameters().put('phone',testCont.Phone);*/
       Cookie tranId = ApexPages.currentPage().getCookies().get('tranId');
    
        // If this is the first time the user is accessing the page, 
        // create a new cookie with name 'counter', an initial value of '1', 
        // path 'null', maxAge '-1', and isSecure 'false'. 
        
            tranId = new Cookie('tranId',testTM.id,null,-1,false);
        
        // If this isn't the first time the user is accessing the page
        // create a new cookie, incrementing the value of the original count by 1
        // Set the new cookie for the page
        ApexPages.currentPage().setCookies(new Cookie[]{tranId});
        Test.startTest();
            ConsumerEntryController controller = new ConsumerEntryController(new ApexPages.StandardController(testCont));
            controller.save();
        Test.stopTest();
       }
     // validate SaveNoAddrVerify method
     static testMethod void validateSaveNoAddrVerify()
      {
       Account testAcc = TestDataSetup.createAccount('Test Account');
       insert testAcc ;
       Date bdate = Date.newInstance(1989, 06, 14);
       Contact testCont = TestDataSetup.createContact('Test Fname','Test Lname',testAcc.Id,true,'20001',bdate,'Test Street', true, true);
        //insert testCont;
        Operating_Company__c testOpCo= TestDataSetup.createOpCo('Telephone', 'Phone USST','Inbound','  PMUSA',true);
        insert testOpCo;
        TFN__c testTFN = TestDataSetup.createTFN(true, '1800', 45, testOpCo);
        insert testTFN;
        Transaction_Management__c testTM= TestDataSetup.createTM(testOpCo, testTFN);
        insert testTM;
        ApexPages.currentPage().getParameters().put('tranid',testTM.Id);
        Test.startTest();
        ConsumerEntryController controller = new ConsumerEntryController(new ApexPages.StandardController(testCont));
        controller.save();
        Test.stopTest();
       }
  }