objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Apt_Lot__c</fullName>
        <label>Apt / Lot</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <encrypted>true</encrypted>
        <label>City  / Locality</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <encrypted>true</encrypted>
        <label>State / Province</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_Address__c</fullName>
        <encrypted>true</encrypted>
        <label>Street Address / Address1</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <encrypted>true</encrypted>
        <label>Zip Code / Postal code</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Correspondence__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Correspondences</relationshipLabel>
        <relationshipName>Correspondences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DocType__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Feed outbound- Correspondence</description>
        <label>Document Type Code</label>
        <referenceTo>DocumentType__c</referenceTo>
        <relationshipLabel>Correspondences</relationshipLabel>
        <relationshipName>Correspondences</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Correspondence</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Correspondence ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Correspondences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Fulfillment__c.object
<CustomObject>
    <fields>
        <fullName>Accnumber__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account number</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Fulfillments</relationshipLabel>
        <relationshipName>Fulfillments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Add1__c</fullName>
        <description>Address 1(always has the street address in this filed)</description>
        <label>Address 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Add2__c</fullName>
        <description>Address 2 (apt or floor number)</description>
        <label>Address 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Correspondence__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Correspondence</label>
        <referenceTo>Correspondence__c</referenceTo>
        <relationshipLabel>Fulfillments</relationshipLabel>
        <relationshipName>Fulfillments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FName__c</fullName>
        <encrypted>true</encrypted>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LName__c</fullName>
        <encrypted>true</encrypted>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Nameprefix__c</fullName>
        <label>Name Prefix</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Packagecode__c</fullName>
        <label>Package Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>ST</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip__c</fullName>
        <label>Zip5</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Fulfillment</label>
    <nameField>
        <displayFormat>F-{0000}</displayFormat>
        <label>Fulfillment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fulfillments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CreateFulfillmentTest.cls
@isTest(SeeAllData=true)
 Public class CreateFulfillmentTest{
      static testmethod void CreateFulfillmentTest1(){
      
      
      account acc=new account();
        acc.Name='priyanka';
        insert acc;
      
      contact con=new contact();
         con.FirstName='shweta';
         con.Accountid=acc.id;
         con.LastName='thakur';
         con.Apt_Lot__c='qwe';
         con.Street_Address__c='altria';
         con.City__c='meerut';    
         con.State__c='up';
         con.Zip_Code__c ='281004';             
         insert con;
      
      Correspondence__c crspdnc=new Correspondence__c();
          crspdnc.contact__c=con.id;
          insert crspdnc;    
          
      /*DocType__c dt=new DocType__c();
          dt.RequiresFulfillment__c='Yes';
          DT.NAME='ASD';
          insert dt;    */
         
      Fulfillment__c fflmt=new Fulfillment__c ();           
          fflmt.Correspondence__c=crspdnc.Id;
          fflmt.Packagecode__c='aaa';
          fflmt.Accnumber__c=con.id;
          fflmt.Add1__c='bbb';
          fflmt.Add2__c='ccc';
          fflmt.City__c='meerut';
          fflmt.FName__c='shweta';
          fflmt.LName__c='thakur';
          fflmt.Nameprefix__c='ddd';
          fflmt.State__c='up';
          fflmt.Zip__c='asdfg';
                   
          insert fflmt ;
        
      }
      
  }