objects/Contact.object
<CustomObject>
    <fields>
        <fullName>AVF_GIID_Received__c</fullName>
        <defaultValue>false</defaultValue>
        <label>AVF/GIID Received</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Reimbursement__c.object
<CustomObject>
    <fields>
        <fullName>Consumer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Consumer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Reimbursements</relationshipLabel>
        <relationshipName>Reimbursements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Reimbursement</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Reimbursement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reimbursements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ContactHelper.cls
public class ContactHelper {
    public void updateReimbursement(Map<id, Contact>  newMap, Map<id, Contact>  oldmap){
        list<Id> contactIdLst = new list<Id>();
        list<Reimbursement__c> lstreimbupdate = new list<Reimbursement__c>();
        for(Contact conObj : newMap.values()){
        	if(conObj.AVF_GIID_Received__c != oldmap.get(conObj.id).AVF_GIID_Received__c && conObj.AVF_GIID_Received__c){
                contactIdLst.add(conObj.id);
            }
            if(contactIdLst != null && contactIdLst.size() > 0){
            	list<Reimbursement__c> lstreimb = [Select Id, Status__c, Consumer__c From Reimbursement__c 
                                                   Where Consumer__c in: contactIdLst];
                if(lstreimb != null && lstreimb.size() > 0){
                    for(Reimbursement__c reimb : lstreimb){
                        reimb.Status__c = 'Age Verified';
                        lstreimbupdate.add(reimb);
                    }
                } 
                if(lstreimbupdate != null && lstreimbupdate.size()>0){
                    list<Database.SaveResult> lstSaveRst = Database.update(lstreimbupdate);
                    system.debug('----lstSaveRst---'+lstSaveRst);
                }
            }
        }
    }
}