objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Operating_Company__c</fullName>
        <label>Operating Company</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Consumer</fullName>
        <active>true</active>
        <label>Consumer</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Operating_Company__c.object
<CustomObject>
    <fields>
        <fullName>Trade__c</fullName>
        <formula>ISPICKVAL(OperatingCompany__c, &apos;Trade&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Trade</label>
        <type>Checkbox</type>
    </fields>
    <label>Operating Company</label>
    <nameField>
        <displayFormat>OpCo - {00000}</displayFormat>
        <label>OperatingCompany</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Operating Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Transaction_Management__c.object
<CustomObject>
    <fields>
        <fullName>Operating_Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Operating Company</label>
        <referenceTo>Operating_Company__c</referenceTo>
        <relationshipLabel>Transaction Managements</relationshipLabel>
        <relationshipName>Transaction_Managements</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Transaction Management</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Transaction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Managements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/customerRecordTypeHelper.cls
Public class customerRecordTypeHelper{

    public static string getCustomerRecordType(String TranId){
    
       List<Transaction_Management__c> TmObj = new List<Transaction_Management__c>([select id,Operating_Company__c, Operating_Company__r.Trade__c 
                                                                                    from Transaction_Management__c 
                                                                                    where id =: TranId]);
         
         
        id consumerRectype = Schema.SObjectType.contact.getRecordTypeInfosByName().get('Consumer').getRecordTypeId();
        id tradeRectype = Schema.SObjectType.contact.getRecordTypeInfosByName().get('Trade Customer').getRecordTypeId();
        
        if(!TmObj.isEmpty() &&  TmObj[0].Operating_Company__c != null){
            if(TmObj[0].Operating_Company__r.Trade__c){
                return tradeRectype;
            }else{
                return consumerRectype;
            }
        }
        
        return '';     
    }
}